version: '3.3'
services:
  app:
    build: .
    command: npm run dev
    container_name: api-authentication
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db-authentication
    restart: always
    environment:
      MYSQL_DATABASE: 'db-authentication'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
volumes:
  my-db:
    driver: local