name: CI/CD Pipeline
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
      
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 14.x
 
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ~/.ssh/id_rsa
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "test"
